# conda env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  {% if cookiecutter.project_packages == "All" -%}
  - pandas-profiling
  - fs
  - jupyterlab
  - jupyter
  - pathlib
  {% elif cookiecutter.project_packages != "All" -%}
  - pandas
  - matplotlib
  - seaborn
  {% endif -%}
  - pip
  - pyprojroot
  - python={{ cookiecutter.python_version }}
  - pip:
    {% if cookiecutter.project_packages == "All" -%}
    - pyhere
    {% endif -%}